version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: DARK0013
      POSTGRES_PASSWORD: ROOT1234
      POSTGRES_DB: SYSTEM_INVENTORY_DB
    ports:
      - "5499:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: